config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :shots do
  	resources :comments, only: [:create, :destroy]
  	member do
  		put "like", to: "shots#like"
  		put "unlike", to: "shots#unlike"
  	end
  end

  resources :users, only: [:show, :edit, :update]

  root "shots#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :shot
end

app/models/shot.rb
class Shot < ApplicationRecord
	validates :title, presence: true, length: {minimum: 5}
	validates :description, presence: true
	validates :link, presence: true

	mount_uploader :image, PhotoUploader

	is_impressionable

	acts_as_votable
	
	belongs_to :user
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  acts_as_voter

  mount_uploader :avatar, AvatarUploader
  
  has_many :shots, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	before_action :authenticate_user!, only: [:create, :destroy]
	before_action :find_comment, only: [:create, :destroy]

	def create
		@comment = @shot.comments.build(comment_params) # creates the comment on the shot passing in params
		@comment.user_id = current_user.id if current_user # assigns logged in user's ID to comment
		@comment.save!
		redirect_to shot_path(@shot)
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to shot_path(@shot)
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

	def find_comment
		@shot = Shot.find(params[:shot_id]) # finds the shot with the associated shot_id
	end

end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController

	before_action :find_shot, only: [:show, :edit, :update, :destroy, :like, :unlike]
	before_action :authenticate_user!, except: [:index, :show]
	impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :session_hash]

	def index
		@shots = Shot.order("created_at DESC")
		@jumbotron = true
	end

	def new
		@shot = current_user.shots.build
	end

	def create
		@shot = current_user.shots.build(shot_params)
		if @shot.save
			redirect_to shots_path, notice: "Shot 已建立。"
		else
			render :new, alert: "Shot 建立失敗。"
		end
	end

	def show
		@comment = Comment.new
	end

	def edit
	end

	def update
		if @shot.update(shot_params)
			redirect_to shot_path(@shot), notice: "Shot 已修改。"
		else
			render :edit, alert: "Shot 修改失敗。"
		end
	end

	def destroy
		@shot.destroy
		redirect_to shots_path, alert: "Shot 已刪除!"
	end

	def like
		@shot.liked_by current_user
		respond_to do |format|
			format.html { redirect_back fallback_location: root_path}
		end
	end

	def unlike
		@shot.unliked_by current_user
		respond_to do |format|
			format.html { redirect_back fallback_location: root_path}
		end
	end

	private

	def shot_params
		params.require(:shot).permit(:title, :description, :link, :image)
	end

	def find_shot
		@shot = Shot.find_by(id: params[:id])
		if @shot.blank?
			redirect_to root_path
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :find_user, only: [:show, :edit, :update]

	def show
	end

	def edit
		unless @user == current_user
			redirect_to user_path(@user)
		end
	end

	def update
		@user.update(user_params)
		redirect_to user_path(@user)
	end

	private

	def find_user
		@user = User.find_by(id: params[:id])
		if @user.blank?
			redirect_to root_path
		end
	end

	def user_params
		params.require(:user).permit(:name, :intro, :avatar)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def verbose_data(data)
		data.strftime("%B %d, %Y")
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment_form.html.erb
<%= form_for [@shot, @comment] do |f| %>
	<div class="form-group">
		<%= f.text_area :content, placeholder: "請留言!", rows: "4", class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.submit class: "btn btn-success btn-sm" %>
	</div>
<% end %>

app/views/comments/_comment_input.html.erb
<%= form_for [@shot, @comment] do |f| %>
	<div class="form-group">
		<%= f.text_area :content, placeholder: "請留言!", class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.submit class: "btn btn-success btn-sm" %>
	</div>
<% end %>

app/views/comments/_comment_show.html.erb
<% @shot.comments.each do |comment| %>
	<div>
		<h6><strong><%= comment.user.name %></h6></strong>
		<p><%= simple_format(comment.content) %></p>
		<em><%= time_ago_in_words(comment.created_at) %> ago</em>
		<% if user_signed_in? && (current_user.id == comment.user_id) %>
			<%= link_to "Delete", shot_comment_path(@shot, comment), method: :delete, class: "text_pink" %>
		<% end %>
	</div>
	<hr>
<% end %>

app/views/layouts/_jumbotron.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron jumbotron-fluid">
    <div class="container text-center">
      <p class="lead">
        <strong>What are you working on?</strong>
        Share your inspiration and see what's inspiring others.
      </p>
      <%= link_to "Log in", new_user_session_path, class: "btn btn-pink" %>
    </div>
  </div>
<% end %>

app/views/layouts/_message.html.erb
<% if flash[:notice] %>
  <div class="alert alert-pink alert-dismissible fade show" role="alert">
    <strong><%= notice %></strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-persimmon alert-dismissible fade show" role="alert">
    <strong><%= alert %></strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm sticky-top navbar-dark bg-dark">
  <%= link_to shots_path, class: "navbar-brand" do %>
    <i class="fab fa-dribbble"></i>Dribbble Clone
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item mr-auto active">
        <%= link_to "Shots", shots_path, class: "nav-link color-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to new_shot_path, class: "nav-link btn btn-pink btn-sm" do %>
            <i class="fa fa-upload"></i>New Shot
          <% end %>
        </li>
        <!-- <li class="nav-item nav-name"> -->
          <%#= link_to "Account Settings", edit_user_registration_path, class: "nav-link" %>
          <%#= link_to current_user.name, user_path(current_user), class: "nav-link" %>
        <!-- </li> -->
        <li class="nav-item dropdown nav-name">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.avatar.blank? %>
              <img src="http://via.placeholder.com/20x20" class= "user_small_image">
            <% else %>
              <%= image_tag current_user.avatar_url, class: "user_small_image" %>
            <% end %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to current_user.name, user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Account Settings", edit_user_registration_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dribbble</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <% if @jumbotron %>
      <%= render "layouts/jumbotron" %>
    <% end %>
    <%= render "layouts/message" %>
    <%= yield %>
  </body>
</html>

app/views/shots/_form.html.erb
<section id="shots_form">
	<div class="row">
		<div class="col-12 col-md-12">
			<% if @shot.errors.any? %>
			  <div class="alert alert-persimmon alert-dismissible fade show" role="alert">
			  	<ul class="mb-0">
			  		<% @shot.errors.full_messages.each do |msg| %>
			  			<li><%= msg %></li>
						<% end %>
			  	</ul>
			    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
			      <span aria-hidden="true">&times;</span>
			    </button>
			  </div>
			<% end %>
			<%= form_for @shot do |f| %>
				<div class="container">
					<div class="row">
						<div class="col-12 col-md-4 d-flex flex-column justify-content-start">
							<div class="form-group mt-5 mb-0">
								<% if @shot.image.blank? %>
									<img src="http://via.placeholder.com/350x250" id="target" class="img-fluid">
								<% else %>
									<%= image_tag @shot.image_url, class: "img-fluid", id: "target", original_url: @shot.image_url %>
								<% end %>
							</div>
							<div class="form-group">
								<div class="custom-file">
									<%= f.label :image, "Image", class: "custom-file-label" %>
									<%= f.file_field :image, accept: "image/gif, image/jpeg, image/png" , class: "custom-file-input" %>
								</div>
							</div>
						</div>

						<div class="col-12 col-md-8 d-flex flex-column justify-content-center form_center">
							<div class="form-group">
								<%= f.label :title, "Title：" %>
								<%= f.text_field :title, class: "form-control" %>
							</div>
							<div class="form-group">
								<%= f.label :description, "Description：" %>
								<%= f.text_area :description, rows: "15", class: "form-control" %>
							</div>
							<div class="form-group">
								<%= f.label :link, "Link：" %>
								<%= f.text_field :link, class: "form-control" %>
							</div>
							<div class="form-group">
								<%= f.submit class: "btn btn-success btn-lg" %>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</section>

<script>
	$(function(){
		$("#shot_image").change(function(){
			readURL(this, "target");
		});

		function readURL(input, image_tag_id){
			if(input.files && input.files[0]){
				var reader = new FileReader();
				reader.onload = function (e){
					$("#" + image_tag_id).attr('src', e.target.result);
				}
				reader.readAsDataURL(input.files[0]);
			} else {
				var original_url = $("#" + image_tag_id).attr("original_url");
				$("#" + image_tag_id).attr('src', original_url);
			}
		}
	});
</script>

app/views/shots/edit.html.erb
<%= render "form" %>

app/views/shots/index.html.erb
<section id="shots_index">
	<div class="container">
		<div class="row">

			<% @shots.each do |shot| %>
				<div class="col-12 col-md-3">
					<%= link_to shot_path(shot), class: "card mt-4" do %>
					  <%= image_tag shot.image_url, class: "card-img-top" %>
					  <div class="content">
					  	<h6><%= truncate(shot.title, length: 19) %></h6>
					  	<p class="text-muted"><%= truncate(shot.description, length: 110) %></p>
					  </div>
					  <div class="card-body text-muted d-flex justify-content-end">
					    <p><i class="fas fa-eye"></i><%= shot.impressionist_count %></p>
					    <p><i class="fa fa-comment"></i><%= shot.comments.count %></p>
					    <p>
					    	<% if user_signed_in? %>
						    	<% if current_user.liked? shot %>
						    		<i class="fa fa-heart unlike_shot"></i><%= shot.get_likes.size %>
						    	<% else %>
						    		<i class="fa fa-heart like_shot"></i><%= shot.get_likes.size %>
						    	<% end %>
						    <% else %>
						    	<i class="fa fa-heart like_shot"></i><%= shot.get_likes.size %>
						    <% end %>
					    </p>
					  </div>
					<% end %>
					<div class="text-center mt-2">
						<% if shot.user.avatar_url.blank? %>
              <img src="http://via.placeholder.com/20x20" class= "user_small_image">
            <% else %>
              <%= image_tag shot.user.avatar_url, class: "user_small_image" %>
            <% end %>
						<p class="user_name"><%= shot.user.name %></p>
					</div>
					<!-- <h6 class="text-center mt-2"><%#= shot.user.name %></h6> -->
				</div>
			<% end %>

		</div>
	</div>
</section>

<!-- current_user.id == @shot.user.id -->

app/views/shots/new.html.erb
<%= render "form" %>

app/views/shots/show.html.erb
<section id="shots_show">
	<div class="container">
		<div class="col-12 col-md-10 offset-md-1">
			<div class="row">

				<div class="col-12 col-md-12">
					<h1><%= @shot.title %></h1>
					<div class="text-muted">
						by<strong><%= @shot.user.name %></strong>
						posted <%= verbose_data(@shot.created_at) %>
					</div>
				</div>

				<div class="col-12 col-md-8">
					<div class="show_img">
						<%= image_tag @shot.image_url, class: "img-fluid" %>
					</div>
					<div class="show_content">
						<%= simple_format @shot.description %>
						<hr>
					</div>
					<div class="comment">
						<h4><%= pluralize(@shot.comments.count, "Comments") %></h4>
						<%= render "comments/comment_show" %>
						<% if user_signed_in? %>
							<%= render "comments/comment_form" %>
						<% else %>
						<div class="comment_item">
							<%= link_to 'Log in', new_user_session_path, class: "text_pink" %> to leave a comment.
						</div>
						<% end %>
					</div>
				</div>

				<div class="col-12 col-md-4 text-muted d-none d-sm-block">
					<ul class="list-group list-group-flush">
					  <li class="list-group-item d-flex justify-content-between align-items-center">
					  	<% if user_signed_in? %>
						  	<% if current_user.liked? @shot %>
						  		<%= link_to unlike_shot_path(@shot), method: :put, class: "unlike_shot" do %>
								  	<span><i class="fa fa-heart unlike_shot"> Like</i></span>
								  <% end %>
							  <% else %>
							  	<%= link_to like_shot_path(@shot), method: :put, class: "like_shot" do %>
								  	<span><i class="fa fa-heart like_shot"> Like?</i></span>
								  <% end %>
						  	<% end %>
						  			<span><%= pluralize(@shot.get_likes.size, "likes") %></span>
						  <% else %>
						  	<%= link_to like_shot_path(@shot), method: :put, class: "like_shot" do %>
						  		<span><i class="fa fa-heart like_shot"> Like?</i></span>
						  	<% end %>
						  	<span><%= pluralize(@shot.get_likes.size, "likes") %></span>
						  <% end %>
					  </li>
					  <li class="list-group-item d-flex justify-content-between align-items-center">
					  	<span><i class="fa fa-comment"> Comment</i></span>
					  	<span><%= pluralize(@shot.comments.count, "comments") %></span>
					  </li>
					  <li class="list-group-item d-flex justify-content-between align-items-center">
					  	<span><i class="fas fa-eye"> Views</i></span>
					  	<span><%= pluralize(@shot.impressionist_count, "views") %></span>
					  </li>
					  <li class="list-group-item">
					  	<%= link_to "Visit Link", @shot.link, class: "btn btn-secondary btn-sm btn-block", target: "_blank" %>
					  </li>
					  <% if user_signed_in? && (current_user.id == @shot.user.id) %>
						  <li class="list-group-item text-center">
						  	<div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
								  <%= link_to "Edit", edit_shot_path(@shot), class: "btn btn-outline-danger" %>
								  <%= link_to "Delete", shot_path(@shot), method: :delete, data: {confirm: "Are you sure ?"}, class: "btn btn-outline-danger" %>
								</div>
						  </li>
						<% end %>
					</ul>
				</div>

			</div>
		</div>
	</div>
</section>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
     <div class="col-md-6 offset-md-3 user_edit">
       <h3>Edit Profile</h3>
       <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :intro, "自我介紹" %>
          <%= f.text_area :intro, rows: "7", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :avatar, "大頭照上傳" %>
          <%= f.file_field :avatar %>
        </div>
        <div class="form-group">
          <%= f.submit "Update", class: "btn btn-primary" %>
          <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
        </div>
      <% end %>
     </div>
   </div>
</div>

app/views/users/show.html.erb
<section class="users_show">
	<div class="container">
		<div class="col-12 col-md-8 offset-md-2">

			<div class="row user_header">
				<div class="col-12 col-md-4">
					<% if @user.avatar.blank? %>
						<div class="text-center">
							<img src="http://via.placeholder.com/350x350" class="img-fluid img-thumbnail">
						</div>
					<% else %>
						<%= image_tag @user.avatar_url, class: "img-fluid" %>
					<% end %>
				</div>

				<div class="col-12 col-md-8">
					<div class="text-left">
						<h1><%= @user.name %></h1>
						<h6 class="card-subtitle mb-2 text-muted"><%= @user.email %></h6>
						<p class="lead"><%= @user.intro %></p>
						<% if user_signed_in? && (current_user.id == @user.id) %>
							<%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-primary" %>
						<% end %>
					</div>
				</div>
			</div>
		
		</div>
	</div>
</section>